### ISSUE TITLE
Custom metric not registered

### ISSUE THREAD

**Issue by BlueSkunka** [artprima/prometheus-metrics-bundle#102]
I tried to add my custom metric following the `README.md` example: 

```php
<?php

namespace App\Metrics;

// ...

class CustomMetricCollector implements RequestMetricsCollectorInterface, TerminateMetricsCollectorInterface
{
    private String $namespace;
    private CollectorRegistry $collectionRegistry;

    public function __construct(private CategoryRepository $categoryRepository)
    {
    }

    public function init(string $namespace, CollectorRegistry $collectionRegistry): void
    {
        $this->namespace = $namespace;
        $this->collectionRegistry = $collectionRegistry;
    }

    // Default incRequest and incResponse methods 

    private function incCategoryCount(string $category): void
    {
        $counter = $this->collectionRegistry->getOrRegisterCounter(
            $this->namespace, 
            'category_add_manga', 
            'category count'
        );

        $counter->inc([sprintf('%s', $category)]); 
    }

    // called on the `kernel.request` event
    public function collectRequest(RequestEvent $event): void
    {
        $request = $event->getRequest();
        $requestMethod = $request->getMethod();
        $requestRoute = $request->attributes->get('_route');

        // do not track "OPTIONS" requests
        if ('OPTIONS' === $requestMethod) {
            return;
        }

        $this->incRequestsTotal($requestMethod, $requestRoute);

        if ($requestRoute == "api_categories_add_manga" && $requestMethod == "PUT") {
            $attributes = $request->attributes->get('_route_params');
            $category = $this->categoryRepository->find($attributes['categoryId']);

            $this->incCategoryCount($category->getName());
        }
    }

}
```

On `PUT 'api_categories_add_manga'` request, I want to increment specific metric with the category name to track new manga trends. 

I send my request which is successfull and I see the `'myapp_http_requests_total{action="PUT-api_categories_add_manga"}'` metric incrementing when I request `'/metrics/prometheus'` but I can't see my custom metric:

```yaml
# HELP myapp_http_2xx_responses_total total 2xx response count
# TYPE myapp_http_2xx_responses_total counter
myapp_http_2xx_responses_total{action="POST-api_login"} 1
myapp_http_2xx_responses_total{action="PUT-api_categories_add_manga"} 3
myapp_http_2xx_responses_total{action="all"} 4
# HELP myapp_http_requests_total total request count
# TYPE myapp_http_requests_total counter
myapp_http_requests_total{action="POST-api_login"} 2
myapp_http_requests_total{action="PUT-api_categories_add_manga"} 7
myapp_http_requests_total{action="all"} 9
# HELP myapp_http_responses_total total response count
# TYPE myapp_http_responses_total counter
myapp_http_responses_total{action="POST-api_login"} 1
myapp_http_responses_total{action="PUT-api_categories_add_manga"} 3
myapp_http_responses_total{action="all"} 4
# HELP myapp_instance_name app instance name
# TYPE myapp_instance_name gauge
myapp_instance_name{instance="d2f6955e7a42"} 1
# HELP myapp_request_durations_histogram_seconds request durations in seconds
# TYPE myapp_request_durations_histogram_seconds histogram
# myapp_http_request_durations_xxx metrics ...
```

I make sure by adding a `dd('hi')` within `incCategoryCount` function that the code was reached and it is. 

Did I missed something ?

**Comment by denisvmedia** [comment]
I can see `private String $namespace;` - I think it should be `private string $namespace;` instead. Not sure, if it's the case, but try changing it.

**Comment by BlueSkunka** [comment]
I changed to `private string $namespace`. New request to my endpoint but my metric is not registered. 

I made sur again that I reached the counter:
![image](https://github.com/user-attachments/assets/0ddbaa22-91f7-4d7d-84e1-b3307f0c8d2c)

**Comment by denisvmedia** [comment]
Can you show your config for this bundle?

**Comment by BlueSkunka** [comment]
I kept the default config:
```yaml
artprima_prometheus_metrics:
    namespace: myapp
    storage: '%env(PROM_METRICS_DSN)%'

    ignored_routes:
        - prometheus_bundle_prometheus
        - _wdt

    # used to disable default application metrics
    #disable_default_metrics: false

    # Recommended to disable default metrics from promphp/prometheus_client_php
    # see https://github.com/PromPHP/prometheus_client_php/issues/62
    disable_default_promphp_metrics: true

    # used to enable console metrics
    #enable_console_metrics: false

when@test:
    artprima_prometheus_metrics:
        storage: in_memory
```
Here's my `.env` file:

```yaml
APP_ENV=dev

###> artprima/prometheus-metrics-bundle ###
PROM_METRICS_DSN=apcu
###< artprima/prometheus-metrics-bundle ###
```

Maybe I should precise that I use a Docker Compose environment: 

```yaml
services:
  symfony-php:
    build:
      context: ./infra/dev/symfony-php
    volumes:
      - ./infra/volumes/dev/composer:/root/.composer
      - ./infra/dev/symfony-php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./api:/var/www/api
    environment:
      APP_ENV: dev
    depends_on:
      - mariadb
    tty: true

  symfony-nginx:
    image: nginx:latest
    volumes:
      - ./infra/volumes/dev/logs/nginx:/var/log/nginx
      - ./infra/dev/symfony-nginx/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api:/var/www/api
    ports:
      - "80:80"
    depends_on:
      - symfony-php
    tty: true

```
I kept only relevants services, the bundle was installed on `symfony-php` service.
