### ISSUE TITLE
Evaluate adapter in runtime

### ISSUE THREAD

**Issue by Johnmeurt** [artprima/prometheus-metrics-bundle#64]
In v1.13 the bundle declare the abstract adapter during container compilation.
This has 2 (negative) impacts:
- The usage of env vars will fail the compilation. You can not let the environment decides the type of storage.
- You have no access to create your custom storage adapter.

The second point is a bonus but the first one will allow OP team to manage the storage.
The goal would be to add storage factory to let evaluation of adapter at runtime.
This will allow config like:
```yaml
artprima_prometheus_metrics:
    namespace: myapp
    storage: "%env(TESTS_STORAGE_URL)%"
    ignored_routes: []
```
or
```yaml
artprima_prometheus_metrics:
    namespace: myapp
    storage: 
       url: "%env(TESTS_STORAGE_URL)%"
       foo: bar
    ignored_routes: []
```
or
```yaml
artprima_prometheus_metrics:
    namespace: myapp
    storage: 
       type: "%env(TESTS_STORAGE_TYPE)%"
       foo: bar
    ignored_routes: []
```
It would make possible to provide a custom adapter: 
```yaml
services:
    DummyAdapterFactory: 
       tags: 
           - { name: "prometheus_metrics_bundle.adapter_factory" }
```

The parameters `type` and `redis` could be deprecated and merged under `storage` parameter.
I think this could be done without BCBreaks. I can provide a PR if this ticket is relevant.
