### ISSUE TITLE
Update symfony/recipes-contrib

### ISSUE THREAD

**Issue by Johnmeurt** [artprima/prometheus-metrics-bundle#75]
Hello,

The recipes of the v1.14 could be changed to include env var. This could look like:
```yaml
artprima_prometheus_metrics:
    namespace: myapp
    storage: '%env(PROM_METRICS_DSN)%'

    ignored_routes:
        - prometheus_bundle_prometheus
        - _wdt

    # used to disable default application metrics
#    disable_default_metrics: false

    # used to disable default metrics from promphp/prometheus_client_php
    disable_default_promphp_metrics: true

    # used to enable console metrics
#    enable_console_metrics: false

when@test:
    artprima_prometheus_metrics:
        storage: in_memory
```

and the manifest:
```yaml
{
    "bundles": {
        "Artprima\\PrometheusMetricsBundle\\ArtprimaPrometheusMetricsBundle": ["all"]
    },
    "copy-from-recipe": {
        "config/": "%CONFIG_DIR%/"
    },
    "env": {
        "PROM_METRICS_DSN": "apcu"
    }
}
```

The test config file could be removed.  Event the section with the `when@test` could be removed but I am not sure it is possible to generate a `.env.test` file.

I thought that was a better idea to submit change here for review / validation before submit a PR on the `recipes-contrib` repository.
