### ISSUE TITLE
Allows use en env var for the namespace

### ISSUE THREAD

**Issue by Johnmeurt** [artprima/prometheus-metrics-bundle#80]
Hello,

I have a case where my app is a kinda polymorph on prod env (ex: features toggle). In this case I wish my app send metrics on a different namespace.

The namespace is a compiled var (and should stay like this) so the only way to do this is to use parameter and override the value on a new env name section. 
ex:
```yaml
parameters:
  prom.namespace: my_namespace

when@featureA_enabled:
  parameters:
    prom.namespace: my_namespace_A
```

A simpliest way to do this would be to use env var even if the namespace should stay a compile var.
Features will be enable by var it could make sense to use env var to change the namespace.

Does anyone have that kind of use case ?
