### ISSUE TITLE
`storage` does not allow resolving ENV parameters

### ISSUE THREAD

**Issue by mvhirsch** [artprima/prometheus-metrics-bundle#96]
Hey :-) 

we're using Symfony CLI and additionally added a password to our setup. This results in a custom environment variable, which needs to be resolved:

```yaml
# config/services.yaml
parameters:
  env(REDIS_DSN): "%env(REDIS_SCHEME)%://%env(REDIS_PASSWORD)%@%env(REDIS_HOST)%:%env(int:REDIS_PORT)%"
  app.redis_dsn: '%env(resolve:REDIS_DSN)%'
```

```yaml
# config/packages/prometheus_metrics.yaml
artprima_prometheus_metrics:
    storage: '%app.redis_dsn%'
```

Sadly it does not recognize the authentication string and fails connecting to redis. Looks like the Extension does not resolve env variables at all, just passing them to the Factory:

https://github.com/artprima/prometheus-metrics-bundle/blob/7a262f7e5deed3efad79ce91c75527caedafbb30/DependencyInjection/ArtprimaPrometheusMetricsExtension.php#L67-L75

**Comment by Johnmeurt** [comment]
Hello,

the extension is not supposed to resolve env vars, it is the container job. That's why factory layer has been added.
What happened if you set your env var like this:

```yaml
artprima_prometheus_metrics:
    storage: '%env(resolve:REDIS_DSN)%'
   # OR
   storage: "%env(REDIS_SCHEME)%://%env(REDIS_PASSWORD)%@%env(REDIS_HOST)%:%env(int:REDIS_PORT)%"
```

**Comment by Johnmeurt** [comment]
Hum,
`'%env(resolve:REDIS_DSN)%'` will not match  your parameter `env(REDIS_DSN)`. It will result with the value of the env var `REDIS_DSN` in your parameter `app.redis_dsn`.

If you want to use env var named REDIS_DSN :
```yaml
storage: '%env(REDIS_DSN)%'  # should be like this: "redis://%env(REDIS_PASSWORD)%@%env(REDIS_HOST)%:%env(int:REDIS_PORT)%"
```

Or simply use your redis env vars:
```yaml
storage:
        type: redis
        host: %env(REDIS_HOST)%
        port: %env(int:REDIS_PORT)%
        password: %env(REDIS_PASSWORD)%
```
